# version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/local/app/Dockerfile
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    networks:
      - app_network
  webserver:
    build: ./docker/local/nginx
    tty: true
    ports:
      - "3456:80"
    volumes:
      - ./docker/local/nginx/conf.d:/etc/nginx/conf.d
      - ./:/app
      - ./docker/local/nginx/logs/:/var/logs/nginx/
    networks:
      - app_network
  redis:
    build: ./docker/local/redis
    volumes:
      - redis_data:/var/lib/redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge